name: build targets
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Build
        run: cargo build --tests --workspace
      - name: Test
        run: cargo test --workspace

      - name: Publish crate
        run: |
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        if: startsWith(github.event.ref, 'refs/tags/v')
